spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
